In [139]:
import numpy as np
a = np.arange(1024).reshape(32,32)  
print (a)

[[   0    1    2 ...   29   30   31]
 [  32   33   34 ...   61   62   63]
 [  64   65   66 ...   93   94   95]
 ...
 [ 928  929  930 ...  957  958  959]
 [ 960  961  962 ...  989  990  991]
 [ 992  993  994 ... 1021 1022 1023]]


In [153]:
out = np.zeros((2,2))
main_out = np.zeros((16,16))
row_stride = -2;
for row in range (16):
    row_stride = row_stride+2
    col_stride = -2;
    for col in range (16):
        col_stride = col_stride +2
        for i in range(2):
            for j in range(2):
                out[i,j]= a[row_stride+i,col_stride+j]
        main_out[row,col] = np.max(out)

print(main_out)
print(main_out.shape)

[[  33.   35.   37.   39.   41.   43.   45.   47.   49.   51.   53.   55.
    57.   59.   61.   63.]
 [  97.   99.  101.  103.  105.  107.  109.  111.  113.  115.  117.  119.
   121.  123.  125.  127.]
 [ 161.  163.  165.  167.  169.  171.  173.  175.  177.  179.  181.  183.
   185.  187.  189.  191.]
 [ 225.  227.  229.  231.  233.  235.  237.  239.  241.  243.  245.  247.
   249.  251.  253.  255.]
 [ 289.  291.  293.  295.  297.  299.  301.  303.  305.  307.  309.  311.
   313.  315.  317.  319.]
 [ 353.  355.  357.  359.  361.  363.  365.  367.  369.  371.  373.  375.
   377.  379.  381.  383.]
 [ 417.  419.  421.  423.  425.  427.  429.  431.  433.  435.  437.  439.
   441.  443.  445.  447.]
 [ 481.  483.  485.  487.  489.  491.  493.  495.  497.  499.  501.  503.
   505.  507.  509.  511.]
 [ 545.  547.  549.  551.  553.  555.  557.  559.  561.  563.  565.  567.
   569.  571.  573.  575.]
 [ 609.  611.  613.  615.  617.  619.  621.  623.  625.  627.  629.  631.
   633.  635.  63